import os.path
__dir__ = os.path.split(os.path.abspath(os.path.realpath(__file__)))[0]
data_location = os.path.join(__dir__, "resources")
src = "https://github.com/lowRISC/opentitan"

# Module version
version_str = "0.0.post12906"
version_tuple = (0, 0, 12906)
try:
    from packaging.version import Version as V
    pversion = V("0.0.post12906")
except ImportError:
    pass

# Data version info
data_version_str = "0.0.post12764"
data_version_tuple = (0, 0, 12764)
try:
    from packaging.version import Version as V
    pdata_version = V("0.0.post12764")
except ImportError:
    pass
data_git_hash = "8dd1ba85f826fc95cc43e55c5dbca20f1614288b"
data_git_describe = "v0.0-12764-g8dd1ba85f8"
data_git_msg = """\
commit 8dd1ba85f826fc95cc43e55c5dbca20f1614288b
Author: Drew Macrae <drewmacrae@google.com>
Date:   Thu Jun 30 14:44:41 2022 -0400

    [ci] Ran buildifier and autogenerated headers based on previous commit
    
    Signed-off-by: Drew Macrae <drewmacrae@google.com>

"""

# Tool version info
tool_version_str = "0.0.post142"
tool_version_tuple = (0, 0, 142)
try:
    from packaging.version import Version as V
    ptool_version = V("0.0.post142")
except ImportError:
    pass


def data_file(f):
    """Get absolute path for file inside pythondata_misc_opentitan."""
    fn = os.path.join(data_location, f)
    fn = os.path.abspath(fn)
    if not os.path.exists(fn):
        raise IOError("File {f} doesn't exist in pythondata_misc_opentitan".format(f))
    return fn
