import os.path
__dir__ = os.path.split(os.path.abspath(os.path.realpath(__file__)))[0]
data_location = os.path.join(__dir__, "resources")
src = "https://github.com/lowRISC/opentitan"

# Module version
version_str = "0.0.post12874"
version_tuple = (0, 0, 12874)
try:
    from packaging.version import Version as V
    pversion = V("0.0.post12874")
except ImportError:
    pass

# Data version info
data_version_str = "0.0.post12732"
data_version_tuple = (0, 0, 12732)
try:
    from packaging.version import Version as V
    pdata_version = V("0.0.post12732")
except ImportError:
    pass
data_git_hash = "0a53139eca7223705f510c80e65bbcdb8f33fb40"
data_git_describe = "v0.0-12732-g0a53139eca"
data_git_msg = """\
commit 0a53139eca7223705f510c80e65bbcdb8f33fb40
Author: Timothy Trippel <ttrippel@google.com>
Date:   Fri Jun 17 13:49:46 2022 -0700

    [mask_rom] run E2E tests in DV sim
    
    This updates the dvsim.py configuration file to demo how to run mask ROM
    E2E in DV simulation. additionally, this fixes a bug that was preventing
    the software (backdoor) logging database from being generated by Bazel
    for the mask ROM.
    
    Signed-off-by: Timothy Trippel <ttrippel@google.com>

"""

# Tool version info
tool_version_str = "0.0.post142"
tool_version_tuple = (0, 0, 142)
try:
    from packaging.version import Version as V
    ptool_version = V("0.0.post142")
except ImportError:
    pass


def data_file(f):
    """Get absolute path for file inside pythondata_misc_opentitan."""
    fn = os.path.join(data_location, f)
    fn = os.path.abspath(fn)
    if not os.path.exists(fn):
        raise IOError("File {f} doesn't exist in pythondata_misc_opentitan".format(f))
    return fn
